# you have to create a discord application for that
discord_token = "super_duper_secret_token_that_you_should_never_share"
# trigger for the bot
prefix = "~"
# youtube data api v3 key
youtube_token = "super_duper_secret_token_that_you_should_never_share"
# color for the bot (hex)[https://g.co/kgs/RvXxDR]
color = "ffffff"
